#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
  brew bundle check >/dev/null 2>&1  || {
    echo "==> Installing Homebrew dependencies…"
    brew bundle
  }
fi

if [ -f ".ruby-version" ] && [ -z "$(rbenv version-name 2>/dev/null)" ]; then
  echo "==> Installing Ruby…"
  rbenv install --skip-existing
  which bundle >/dev/null 2>&1  || {
    gem install bundler
    rbenv rehash
  }
fi

if [ -f "Gemfile" ]; then
  echo "==> Installing gem dependencies…"
  bundle check --path vendor/gems >/dev/null 2>&1  || {
    if [ "$(uname -s)" = "Darwin" ]; then
      # messing with `PKG_CONFIG_PATH` is necessary for getting rugged to work
      PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/opt/openssl/lib/pkgconfig bundle install --local --binstubs --path vendor/cache --quiet --without production
    else
      bundle install --local --binstubs --path vendor/cache --quiet --without production
    fi
  }
fi

if [ -f "package.json" ]; then
  echo "==> Installing node dependencies…"
  npm install
fi
